language: csharp
mono: 
  - latest
sudo: required
dotnet: 2.0.0
node_js:
  - "8.9.1"
script:
  - npm install yarn -g
  - yarn
  - cd $TRAVIS_BUILD_DIR/src/Client
  - dotnet restore
  - dotnet fable webpack --output-path $TRAVIS_BUILD_DIR/src/Docker/Client -p
  - cd $TRAVIS_BUILD_DIR/src/Server
  - dotnet restore
  - dotnet build -c Release -o $TRAVIS_BUILD_DIR/src/Docker
  - cd $TRAVIS_BUILD_DIR/src/Docker
  - ls -l
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: $TRAVIS_BUILD_DIR/src/Docker/**
  skip_cleanup: true
  on:
    tags: true
