language: csharp
mono: none
sudo: required
dotnet: 2.0.0
node_js:
  - "8.9.1"
script:
  - npm install yarn -g
  - yarn
  - cd $TRAVIS_BUILD_DIR/src/Client
  - dotnet restore
  - dotnet fable webpack -p
  - cd $TRAVIS_BUILD_DIR/src/Server
  - dotnet restore
  - dotnet build -c Release -o Server_Release
 
